GET http://localhost:3001/user/creditcards/2021-04 HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJlbmF0b2NhbGVibm9ndWVpcmFAcnVpem9ubGluZS5jb20uYnIiLCJpYXQiOjE2MTYyNjE0NjUsImV4cCI6MTYxNzEyNTQ2NX0.NyogTfHISpJXyTfqiauzc9wpkJjkvoM_mn5DqQqdjAc