POST http://localhost:3001/user/paydebit HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1bmlvQGdtYWlsLmNvbSIsImlhdCI6MTYxNjE5NTE3MSwiZXhwIjoxNjE3MDU5MTcxfQ.D2d1oQ0GQNaorV9sjU-Eo-SgmlIXDgV_B0yJikiBosU

{
     "value": 300,
     "description": "Teclado e Monitor"
}