GET http://localhost:3001/user/statement/1614556860/1617235260 HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhZ2FtYUBnYW1hLmNvbSIsImlhdCI6MTYxNjA4MDQ5MywiZXhwIjoxNjE2OTQ0NDkzfQ.5TUzlgsUBOQmWqxbo4B9m3DrcknnKQFDYgsXprKKjzQ