POST http://localhost:3001/user/transfer HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdhYnJpZWxhY2Npb2xpQGdtYWlsLmNvbSIsImlhdCI6MTYxNjM0NzYyMywiZXhwIjoxNjE3MjExNjIzfQ.GgaV4KMmrYdacobrkHLXHMNOYfO3pdpPdw-lOR1K-IA

{
    "destinyAccount": 1,
    "value": 1,
    "CPF": "01196253854",
    "description": "Paulista Infeliz :D"
}

###
POST http://localhost:3001/user/transfer HTTP/1.1
Content-Type: application/json


{
    "destinyAccount": 6,
    "bank": 999,
    "originAccount": 105,
    "value": 10000,
    "CPF": "06889461002"
}

